#! usr/bin/env python

import subprocess
import optparse


# function to get the arguments
def get_arguments():
    parser = optparse.OptionParser()
    parser.add_option('-i', '--interface', dest='interface',
                      help='Interface for which you want to change the MAC address')
    parser.add_option('-m', '--mac', dest='new_mac', help='New MAC address')
    if not options.interface:
        parser.error('Please insert an interface.')
    if not options.new_mac:
        parser.error('Please insert a new MAC address.')
    return options


# function to change the MAC address
def change_mac(interface, new_mac):
    print("Changing MAC address for interface " + interface + " to " + new_mac)
    subprocess.call(['ifconfig', interface, 'down'])
    subprocess.call(['ifconfig', interface, 'hw', 'ether', new_mac])
    subprocess.call(['ifconfig', interface, 'up'])


options = get_arguments()
change_mac(options.interface, options.new_mac)
